ARG RUNPOD_VERSION="2.8.0-py3.11-cuda12.8.1-cudnn-devel-ubuntu22.04"
FROM runpod/pytorch:${RUNPOD_VERSION}

RUN curl -fsSL https://get.docker.com | sh

RUN mkdir -p /etc/docker && echo '{"default-runtime":"nvidia","runtimes":{"nvidia":{"path":"nvidia-container-runtime","runtimeArgs":[]}}}' > /etc/docker/daemon.json
